-- INSERT USERS

insert into users (name, email, password, hash) values ('Mikaela Kinnerley', 'mkinnerley0@bravesites.com', 'c2uJ4rEv','QFoICspAFfDG2iy5zXrv');
insert into users (name, email, password, hash) values ('Patty Woolen', 'pwoolen1@g.co', 'hmMdNwjbXh','NHW77ha3L0Q99OwoAjHj');
insert into users (name, email, password, hash) values ('Gabriela Dackombe', 'gdackombe2@phpbb.com', 'zQaVPDBOvrq','TAxhxkxDIEyxG5tg9lL2');
insert into users (name, email, password, hash) values ('Tiphany Ginglell', 'tginglell3@xinhuanet.com', 'fHWBNtd0cv','e0CHoFUpi2orTnToufmU');
insert into users (name, email, password, hash) values ('Lilyan Eunson', 'leunson4@nbcnews.com', 'khlvOpoqUqx','Yz44ie4yPfTShC5W2JzY');
insert into users (name, email, password, hash) values ('Anjela De Bruijn', 'ade5@php.net', 'v0SAjzjRtYf','QmthFymhpcnwPBmedK0G');
insert into users (name, email, password, hash) values ('Philbert Ickovicz', 'pickovicz6@msu.edu', 'tPOSnPGO1','9gTu9jbBPpI98yKUs3Yb');
insert into users (name, email, password, hash) values ('Doralin Hardin', 'dhardin7@wix.com', 'NhrOr5KvD','9WLgrOm5AWV5ppJr1XGa');
insert into users (name, email, password, hash) values ('Dulcy Do', 'ddo8@fema.gov', 'w6vADgB9','kOa6QZkSo4Dpn4Qr9OVG');
insert into users (name, email, password, hash) values ('Ephrayim Marlow', 'emarlow9@list-manage.com', 'xkc9Io56x','GFZPE0iEiz8YZdX2xAm1');
insert into users (name, email, password, hash) values ('Genni Wernham', 'gwernhama@trellian.com', 'hgoNbq','5XBNZaHRRhM9tJfdDjjz');
insert into users (name, email, password, hash) values ('Mabelle Ousley', 'mousleyb@aol.com', 'tEHQkuh','Nh3h7k3VlIjAo9Ym1aNO');
insert into users (name, email, password, hash) values ('Joleen Brunskill', 'jbrunskillc@google.it', 'INTG0En','pzKL3XRDZpv9UEMQkBl5');
insert into users (name, email, password, hash) values ('Roddie Trematick', 'rtrematickd@domainmarket.com', 'CavHcQJnE8nx','znh4mrV2EOno3FDFAlTI');
insert into users (name, email, password, hash) values ('Barth De Courtney', 'bdee@parallels.com', 'ZDSb5t','fjyvzRj0E5WujorLAgO3');
insert into users (name, email, password, hash) values ('Waly Doogue', 'wdooguef@jimdo.com', '6y8fUYNape9x','m4SoQE9hHJP1RwVzj89A');
insert into users (name, email, password, hash) values ('Baillie Kopfen', 'bkopfeng@twitpic.com', 'jm2YCbzcqM','XcpzfZqqv8pxvGMfi67l');
insert into users (name, email, password, hash) values ('Adelind Gegg', 'ageggh@rediff.com', 'aPEzSEDNfoS','2Vc69a7VuE3EuSC3z8bI');
insert into users (name, email, password, hash) values ('Bard Littley', 'blittleyi@clickbank.net', 'ithmdb7z','JRlsUlEqVnfrZlARuKlA');
insert into users (name, email, password, hash) values ('Britte Lambertson', 'blambertsonj@usnews.com', '3nHGQ5AeC','vnjQzza1KOXwz2mpFlCY');
insert into users (name, email, password, hash) values ('Stormi Fabbro', 'sfabbrok@icio.us', 'HucuYqN0R','DC5GHppCbepO5J7utiZE');
insert into users (name, email, password, hash) values ('Merry Mackett', 'mmackettl@narod.ru', 'bYwEuNDsZTP','yIliq58Fupf04tv7PJSP');
insert into users (name, email, password, hash) values ('Cassandre Norcutt', 'cnorcuttm@wordpress.com', 'N4691Jj9Ya7S','h9H3CipE4fUl2ritKupj');
insert into users (name, email, password, hash) values ('Stevie Shalliker', 'sshallikern@github.com', 'STZnWwHWID','Toi2W8lZezE7UfssJopo');
insert into users (name, email, password, hash) values ('Martguerita Reglar', 'mreglaro@meetup.com', 'vVVabd','NRsN7U437RDVt6V6IgUv');
insert into users (name, email, password, hash) values ('Penrod Skedge', 'pskedgep@geocities.com', 'E2QgdZ','8n2YNiRjjMbz7osHcw4U');
insert into users (name, email, password, hash) values ('Dolores Craister', 'dcraisterq@sciencedirect.com', 'Lg38cfM','T3RkPoPIAzzLYIP1UJfm');
insert into users (name, email, password, hash) values ('Shay Bebbington', 'sbebbingtonr@exblog.jp', '1nvmP4LDn','VfQlzAgvFArInxk1pJ0o');
insert into users (name, email, password, hash) values ('Dukie Hulles', 'dhulless@wsj.com', 'uTmhHg','oA7jP4oaafrXMOEz5CPB');
insert into users (name, email, password, hash) values ('Worden Swalteridge', 'wswalteridget@jalbum.net', 'ZAK1wnz9','oDeMkFygilfcCzC3iKgW');
insert into users (name, email, password, hash) values ('Kissee Carnelley', 'kcarnelleyu@fastcompany.com', 'ONirgbWu','MoX3jZ2crZ7XdCpGuuZg');
insert into users (name, email, password, hash) values ('Codie Krolik', 'ckrolikv@acquirethisname.com', 'kwpB9mxjs3','Ooe2hm8E7cWrWtACyUK2');
insert into users (name, email, password, hash) values ('Ted Filipson', 'tfilipsonw@vinaora.com', 'SIHJqCvgObGd','PwcrE0o5mLH5gaN4snq8');
insert into users (name, email, password, hash) values ('Karyl Maybery', 'kmayberyx@pbs.org', 'MOFnq8d3OH','41oxF9SjR3dqOpilmhN9');
insert into users (name, email, password, hash) values ('Nadine Dovinson', 'ndovinsony@home.pl', 'yBkAOXD','xgbrO7zyiqe0ie2C8B6K');
insert into users (name, email, password, hash) values ('Desi Penketh', 'dpenkethz@goo.ne.jp', 'UHSMOKBzqV','M5rAAQCBeTmkeBVvahbk');
insert into users (name, email, password, hash) values ('Bogey Kondrachenko', 'bkondrachenko10@nymag.com', 'P4Wq4YRkZD','xwgVFpb2qi0ZQhRZgD5B');
insert into users (name, email, password, hash) values ('Ibby Synan', 'isynan11@uol.com.br', '8A4hWpoQhxg','Gyh4sEyHeDzrzpW2pEki');
insert into users (name, email, password, hash) values ('Ashil Fairs', 'afairs12@dailymotion.com', 'NX0gMINE','BVTzAYEeaFQJHVVOwJ40');
insert into users (name, email, password, hash) values ('Ellyn Gaskell', 'egaskell13@amazon.de', '09mqb3D','uTMXwu5g8LwoJ3X7B0gm');
insert into users (name, email, password, hash) values ('Melva Huthart', 'mhuthart14@youtu.be', 'WAUYhmSBQ6DO','bYvqT4vtZHoGdRomsldR');
insert into users (name, email, password, hash) values ('Nikita Slator', 'nslator15@blogspot.com', 'GjVAjB','Mqb2qd9lywLJNsGe9pGI');
insert into users (name, email, password, hash) values ('Daryn Muslim', 'dmuslim16@phoca.cz', 'vO7oMB','STj68gLB8OQS8dVihaEh');
insert into users (name, email, password, hash) values ('Lonnard Lingner', 'llingner17@so-net.ne.jp', 'D6yOzphh','4kIHaURmG90AKpfZAlWe');
insert into users (name, email, password, hash) values ('Fenelia Guiducci', 'fguiducci18@thetimes.co.uk', '7hJuNqexV0','hbhsymSkXcCIKdjUOLFT');
insert into users (name, email, password, hash) values ('Rand Bowart', 'rbowart19@arstechnica.com', '6IYdaEN','PKyOx6q3I4R10KKGE5w2');
insert into users (name, email, password, hash) values ('Elwin Swindall', 'eswindall1a@w3.org', 'LaAx711wB9Js','QASui36LUxbo9KT683zU');
insert into users (name, email, password, hash) values ('Cheston Shortland', 'cshortland1b@intel.com', 'HeFphQXGW','115QCOoUqkCa19ptU7mh');
insert into users (name, email, password, hash) values ('Kirby Soppett', 'ksoppett1c@dropbox.com', 'zxMqrFkT','YITxI03C8BgYgP3Td91o');
insert into users (name, email, password, hash) values ('Cecily Slimon', 'cslimon1d@amazonaws.com', 'KqpYiFQj0qDO','AK8aWKCWbajVxZ6aR0EL');
insert into users (name, email, password, hash) values ('Allegra Tattoo', 'atattoo1e@phpbb.com', 'aH5ZQDDkcFH','XiGc1Aef7eXCNrgd5pq1');
insert into users (name, email, password, hash) values ('Annmarie Cissell', 'acissell1f@de.vu', '6cVsDW7fFvN','b5eCJhLvy6pLoG5azy2i');
insert into users (name, email, password, hash) values ('Calypso Tibbotts', 'ctibbotts1g@nba.com', 'Nku2m21syt','cflHr9g3yzwTgeyoklZV');
insert into users (name, email, password, hash) values ('Ethan Couser', 'ecouser1h@51.la', '4GVR15O8','T2QGAQK7zE0wCq25pt3O');
insert into users (name, email, password, hash) values ('Sabine Smartman', 'ssmartman1i@freewebs.com', 'pk95eHO69','0ptSLDaQJeCnEDQfc2rq');
insert into users (name, email, password, hash) values ('Chas Domerc', 'cdomerc1j@sakura.ne.jp', 'S6OdX4X9u','usX5Temn0aeTBCeoJrqp');
insert into users (name, email, password, hash) values ('Enrika Videan', 'evidean1k@ebay.com', 'Wz83ks','1aCKUOLFRST4fdGO4HFI');
insert into users (name, email, password, hash) values ('Sansone Marshall', 'smarshall1l@youtube.com', 'RxKVRd','tdIUUxnO3TcGMJHmBYre');
insert into users (name, email, password, hash) values ('Estevan Simoncini', 'esimoncini1m@adobe.com', 'Zcu81HjFFOk','1QJfg7Sz6sUlabfvOG9Q');
insert into users (name, email, password, hash) values ('Kathlin Lilywhite', 'klilywhite1n@trellian.com', 'H49vmzZ','ZXDmX30EMO13w2MQZ8wu');
insert into users (name, email, password, hash) values ('Hermon Menghi', 'hmenghi1o@mac.com', 'JeS0zwvSsA','PtcqV38f9UQZklm8h236');
insert into users (name, email, password, hash) values ('Rhiamon Spinke', 'rspinke1p@paypal.com', 's3Ais72RIR','sIc567u9XtCUH7gudmT9');
insert into users (name, email, password, hash) values ('Major Corthes', 'mcorthes1q@cam.ac.uk', '5MmZX7w5s','W8pi45OeSNCDVstKoEIY');
insert into users (name, email, password, hash) values ('Lanni Sargerson', 'lsargerson1r@bbc.co.uk', 'Us87pIa','GrU2M6QGIcXZEsCSv1F7');
insert into users (name, email, password, hash) values ('Chrystel Grahlmans', 'cgrahlmans1s@fema.gov', 'zBDS1xDXSWD','Dv5PiEf8z8jS2aIoECOd');
insert into users (name, email, password, hash) values ('Alverta Cicetti', 'acicetti1t@noaa.gov', 'DnDG5Bvp2eBy','5Kd0Ga7DKba1P8TUyLVb');
insert into users (name, email, password, hash) values ('Lane Sinncock', 'lsinncock1u@msu.edu', 'wcDLEUvR','GDwSicxGarGt810o1ZIx');
insert into users (name, email, password, hash) values ('Berri Pentelo', 'bpentelo1v@globo.com', 'neFUSw','znKI0uiHd2bGa86DMbNC');
insert into users (name, email, password, hash) values ('Margalit Grinyer', 'mgrinyer1w@house.gov', 'qpYun93Wk','8EFOeepUNvXz1NsFDI9v');
insert into users (name, email, password, hash) values ('Judas Berlin', 'jberlin1x@shop-pro.jp', 'iX7De3moD30a','afFQD9RFMKkkKzvd5bq0');
insert into users (name, email, password, hash) values ('Edeline Skells', 'eskells1y@msn.com', 'kJxhZbmv9y','O0bI8vm66K8kzHeHsKSe');
insert into users (name, email, password, hash) values ('Erma Butchard', 'ebutchard1z@hao123.com', '1ugpzeMYu','AprKOhcshaVHqiydPory');
insert into users (name, email, password, hash) values ('Torry Currm', 'tcurrm20@studiopress.com', 's70gaDiofM','BzB6zQ1wLCg5BMYVq1yg');
insert into users (name, email, password, hash) values ('Ignazio Gravenall', 'igravenall21@google.com.hk', 'jOfbPMaf2J','qaOKNsq6CSyfXx3E6jcG');
insert into users (name, email, password, hash) values ('Worthy Goodband', 'wgoodband22@de.vu', 'i4rsBp2','ixnPpuG2PyvpQjOqmcCt');
insert into users (name, email, password, hash) values ('Mildred Bloomfield', 'mbloomfield23@blogger.com', 'oEvlTVR','RDBtwMl5K2peLgGbI2ES');
insert into users (name, email, password, hash) values ('Kermie Legon', 'klegon24@ibm.com', 'LirmqwcyjqO','F9Jr4ELmKDkToN1Gbp1x');
insert into users (name, email, password, hash) values ('Ira Reolfo', 'ireolfo25@baidu.com', 'XhE1tymcIF4','pDWIs5md9iWRmDyS61Ul');
insert into users (name, email, password, hash) values ('Dallas Pulteneye', 'dpulteneye26@wikia.com', 'RuHIxs','vtfnFYJNqG9vUAWUwOEi');
insert into users (name, email, password, hash) values ('Barbaraanne Biles', 'bbiles27@godaddy.com', 'jNgHA0AH','lKuhVwcdBPy463v8Obvb');
insert into users (name, email, password, hash) values ('Stevy Asplen', 'sasplen28@bandcamp.com', 'Jv4Tep2aNUcS','I9uS1eN04srT4KHGaJvN');
insert into users (name, email, password, hash) values ('Robenia Bolle', 'rbolle29@comsenz.com', 'ODcJnGqTJF8L','A0FxzaFn3GDOxJZhPHcV');
insert into users (name, email, password, hash) values ('Daisie Drayn', 'ddrayn2a@washington.edu', '9nzmrnduXH','t2CaUGZt4fuEA7i3qtYM');
insert into users (name, email, password, hash) values ('Falkner Covolini', 'fcovolini2b@360.cn', 'tuGn6pd5Xsd','4JQFD5p7pN0HJPmkSs1i');
insert into users (name, email, password, hash) values ('Stanford Muslim', 'smuslim2c@alexa.com', 'vMI4YUqu','wzwE6BGGNKafwoRnGETI');
insert into users (name, email, password, hash) values ('Burnaby Gostick', 'bgostick2d@purevolume.com', 'sPVbjcqjYe5','WjcC3eRSHMkChzc0uJUO');
insert into users (name, email, password, hash) values ('Adriena Caseri', 'acaseri2e@ycombinator.com', 'vG4WD20NMR','CgH74qXoR3kxmwcBrc8t');
insert into users (name, email, password, hash) values ('Duane Vaneev', 'dvaneev2f@mayoclinic.com', 'buXYzbNEVzh','X9gNB0K7oOvcQySmZPJl');
insert into users (name, email, password, hash) values ('Jessamine Amar', 'jamar2g@drupal.org', 'OiyWBiNuWl','MrgNrKHHbiKwQkoPsU1h');
insert into users (name, email, password, hash) values ('Obadias Terrelly', 'oterrelly2h@clickbank.net', 'C6DbkYj2r','94JoVKRaXumr0itJ0CUU');
insert into users (name, email, password, hash) values ('Christye Grimley', 'cgrimley2i@goodreads.com', 'xL1TtasDXKrX','v2wNwPfWs74JLpjStIAp');
insert into users (name, email, password, hash) values ('Spencer Craggs', 'scraggs2j@jalbum.net', 'exMVLIrL','jyxr6iJxc0eaZWvJU5GK');
insert into users (name, email, password, hash) values ('Ozzy Adamski', 'oadamski2k@washingtonpost.com', '2Fv40VJC','rGD4Kl9sQXr5diY0PK2C');
insert into users (name, email, password, hash) values ('Wallache Keppin', 'wkeppin2l@symantec.com', '1rCGLj2eOwT5','190gJVkM4dSRk8imzIMV');
insert into users (name, email, password, hash) values ('Sergeant Coton', 'scoton2m@sogou.com', 'lAUceAMoV','1TEBMwH6sDyUHl9Nh84A');
insert into users (name, email, password, hash) values ('Pandora Petrakov', 'ppetrakov2n@rakuten.co.jp', 'w6I5lWTIb3','Ek0SjYbYojZoBAPB4G4h');
insert into users (name, email, password, hash) values ('Hew Girogetti', 'hgirogetti2o@aol.com', 'iRaX2KtdD','MmJ8A8LB5Y5hirlfWaaj');
insert into users (name, email, password, hash) values ('Osborne Haistwell', 'ohaistwell2p@deliciousdays.com', 'pskZMZzF4Q','bTOsjxaIlU18m7nCS4Ad');
insert into users (name, email, password, hash) values ('Charis Aykroyd', 'caykroyd2q@about.me', 'UD7v3f4jv0','Db3f5y7m6ycUHZ2RCAtu');
insert into users (name, email, password, hash) values ('Carita Blazic', 'cblazic2r@dion.ne.jp', 'gsIvX4RDNU','J1W5JZKuVTH3hjV67GT8');


-- INSERT VIDEOS
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('dis parturient montes nascetur ridiculus','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',91299,235,53);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('donec ut dolor morbi','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',14869,1045,88);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('enim in tempor turpis nec euismod scelerisque quam turpis','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',47244,514,6);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('nibh fusce lacus purus aliquet','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',16337,962,76);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('nibh in hac habitasse platea dictumst aliquam augue quam','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',74508,704,98);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('ipsum integer a nibh in quis','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',68109,711,63);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('justo pellentesque viverra','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',55462,170,22);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('molestie sed justo pellentesque viverra pede ac','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',4771,950,85);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('pellentesque ultrices phasellus id sapien in sapien','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',21736,852,31);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('turpis elementum ligula vehicula consequat','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',47753,282,30);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',65605,1045,68);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('duis ac nibh fusce lacus purus aliquet','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',26065,666,20);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('est lacinia nisi venenatis tristique fusce congue diam id','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',11107,229,58);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('magna ac consequat metus sapien','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',63218,811,23);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('vitae quam suspendisse potenti nullam porttitor lacus at','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',32834,237,70);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('nisi eu orci mauris lacinia sapien quis libero nullam sit','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',52776,420,66);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('id sapien in sapien iaculis','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',9675,686,53);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('non pretium quis lectus suspendisse potenti in eleifend','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',64902,459,62);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',41865,1105,46);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('ipsum primis in faucibus orci luctus et','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',47929,500,11);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('pede malesuada in imperdiet et','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',3771,951,1);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('vestibulum proin eu','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',98908,146,62);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('sed lacus morbi sem mauris laoreet ut rhoncus aliquet','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',7102,242,15);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('vel lectus in quam fringilla rhoncus','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',96887,543,85);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('nibh ligula nec sem duis aliquam convallis nunc proin at','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',61131,414,24);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('odio porttitor id','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',70976,540,19);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('id consequat in consequat ut nulla sed accumsan','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',74168,806,13);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('eget rutrum at','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',19740,1174,23);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('eget orci vehicula condimentum curabitur in libero ut massa volutpat','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',33221,805,21);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('nullam orci pede venenatis','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',55777,845,46);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('venenatis lacinia aenean sit','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',95983,520,14);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('nisi at nibh in hac habitasse','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',37846,681,57);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('posuere metus vitae ipsum aliquam','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',29204,764,93);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('lacus purus aliquet at feugiat non','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',33306,70,47);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('posuere felis sed lacus morbi sem mauris laoreet ut','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',79164,742,99);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('rutrum rutrum neque aenean auctor gravida','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',75725,582,70);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('ut blandit non interdum in ante','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',83756,181,52);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',97901,804,48);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('eu interdum eu tincidunt in leo maecenas pulvinar lobortis est','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',41406,608,45);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('amet consectetuer adipiscing elit proin','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',65772,545,96);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('hac habitasse platea dictumst aliquam augue quam sollicitudin vitae','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',90161,295,44);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('pretium quis lectus','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',4019,303,33);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('libero non mattis pulvinar','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',66750,1006,62);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('id consequat in consequat ut nulla sed accumsan felis','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',90869,767,22);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('donec ut mauris eget massa tempor convallis nulla neque libero','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',70224,41,29);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('mauris eget massa tempor convallis','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',42451,141,35);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('ligula pellentesque ultrices phasellus','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',21719,128,24);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('enim leo rhoncus sed vestibulum sit','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',92959,829,43);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('turpis sed ante vivamus tortor duis mattis egestas','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',13764,1074,13);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('in felis donec semper sapien a libero nam','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',23536,706,49);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('habitasse platea dictumst morbi vestibulum velit id','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',10902,1146,8);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('maecenas tincidunt lacus at velit','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',84567,551,100);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('tincidunt in leo maecenas','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',45859,982,12);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('consequat lectus in est risus auctor','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',53292,140,25);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('fringilla rhoncus mauris enim leo rhoncus sed vestibulum','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',49337,758,95);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('blandit nam nulla','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',34548,887,58);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('faucibus accumsan odio curabitur','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',24159,420,86);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('scelerisque mauris sit amet eros suspendisse accumsan tortor','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',16310,736,93);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('platea dictumst morbi','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',7756,126,23);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('consequat varius integer ac leo pellentesque ultrices mattis','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',8820,681,49);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('placerat praesent blandit nam nulla integer','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',15847,635,9);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('nibh ligula nec sem duis aliquam convallis','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',45863,771,5);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('id pretium iaculis diam erat fermentum justo','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',38002,56,35);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('sapien placerat ante nulla justo aliquam quis turpis eget','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',55979,1110,77);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',43654,523,28);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('massa volutpat convallis morbi odio','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',31930,310,41);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('at turpis donec posuere metus vitae ipsum aliquam non mauris','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',67636,1162,16);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('eget semper rutrum nulla','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',54974,1196,6);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('pede justo eu massa donec dapibus duis at velit eu','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',24141,925,66);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('lacinia aenean sit amet justo','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',98817,746,56);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('justo maecenas rhoncus aliquam lacus morbi quis tortor id','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',4301,156,5);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('lorem ipsum dolor sit amet consectetuer','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',28464,756,5);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('vel enim sit amet nunc','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',31357,210,51);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('pede venenatis non sodales sed tincidunt eu','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',5439,493,68);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',88342,1172,90);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('nam dui proin leo odio porttitor id consequat in','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',14757,598,54);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('et ultrices posuere','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',56489,475,58);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('ante ipsum primis in faucibus orci luctus et ultrices','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',395,513,28);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('nibh in quis justo maecenas rhoncus aliquam lacus morbi','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',41538,407,72);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('in tempus sit amet sem fusce consequat nulla nisl','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',66744,777,98);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('in hac habitasse platea dictumst maecenas ut massa quis augue','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',84823,1113,85);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('ut erat curabitur gravida','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',36054,754,88);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('posuere metus vitae ipsum','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',60406,888,16);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('varius ut blandit non interdum','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',11340,944,33);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('pede ac diam cras pellentesque volutpat dui maecenas tristique est','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',47554,440,94);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('risus auctor sed tristique in tempus','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',49662,698,84);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('volutpat convallis morbi odio odio','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',84424,709,48);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('donec semper sapien a libero nam dui proin leo odio','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',66451,451,4);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('libero non mattis pulvinar','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',84585,328,92);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('sed ante vivamus tortor duis','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',18365,802,57);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('imperdiet nullam orci pede venenatis non sodales sed','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',56207,1071,59);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('duis mattis egestas metus aenean fermentum donec ut mauris','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',93759,1034,71);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('est quam pharetra','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',78850,707,49);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('felis eu sapien cursus vestibulum','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',14631,688,35);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('non sodales sed','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',60991,286,16);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('tellus nisi eu orci mauris lacinia','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',44903,920,81);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('duis faucibus accumsan odio curabitur convallis duis consequat dui','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',71538,83,92);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('nisl venenatis lacinia aenean','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',21945,1099,72);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('rutrum neque aenean auctor gravida','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',42801,823,69);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('vel accumsan tellus nisi','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',45042,812,2);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('sed ante vivamus tortor duis mattis','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',91351,980,52);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('rutrum ac lobortis','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',43008,137,34);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('consequat dui nec','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',76276,893,57);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('imperdiet nullam orci pede venenatis non sodales sed','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',75745,639,77);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('quis turpis eget elit sodales scelerisque mauris sit','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',19890,1115,95);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',27876,867,71);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('amet sem fusce consequat nulla nisl','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',9950,895,74);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('ante ipsum primis in faucibus orci luctus et','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',98937,973,28);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('eu felis fusce posuere felis sed lacus','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',60710,956,4);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('sed accumsan felis ut','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',6723,446,74);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('donec posuere metus vitae ipsum aliquam non mauris morbi non','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',92572,395,47);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('consectetuer eget rutrum at lorem integer tincidunt ante','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',69215,648,38);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('phasellus sit amet erat nulla tempus vivamus','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',76282,1019,23);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('in quis justo maecenas','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',99832,536,43);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('et commodo vulputate justo in blandit','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',58712,1161,51);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('pede justo lacinia eget tincidunt eget tempus vel pede','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',42676,627,97);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('tempus vel pede morbi porttitor lorem id ligula suspendisse ornare','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',22860,344,19);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('suscipit nulla elit ac nulla sed vel enim sit amet','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',6428,78,89);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('a odio in hac habitasse','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',60371,539,90);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('felis ut at dolor quis odio','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',83644,527,74);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('aliquet massa id lobortis convallis tortor risus dapibus augue vel','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',46546,1031,27);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('accumsan tortor quis','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',28592,55,61);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('orci luctus et ultrices posuere cubilia curae mauris','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',13865,1097,79);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('turpis adipiscing lorem vitae mattis nibh ligula nec sem duis','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',25767,541,35);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('justo sit amet sapien dignissim vestibulum vestibulum ante','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',14092,398,55);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('condimentum id luctus nec molestie sed justo pellentesque viverra pede','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',53860,201,85);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('tincidunt in leo maecenas','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',69024,671,1);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('ornare imperdiet sapien urna','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',72617,55,17);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('curabitur convallis duis consequat','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',75776,965,20);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('mauris sit amet eros suspendisse accumsan tortor quis turpis','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',899,459,97);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('sit amet diam in magna bibendum imperdiet nullam orci','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',33411,87,82);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('elementum pellentesque quisque porta volutpat erat quisque','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',17580,338,61);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('rhoncus aliquet pulvinar','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',6446,487,94);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('nulla elit ac nulla sed vel enim sit','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',95693,1071,37);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('mi sit amet lobortis sapien sapien non','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',59245,1183,81);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('maecenas tristique est et tempus semper est','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',58506,692,13);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('lobortis sapien sapien non mi integer ac neque duis','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',87700,326,11);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',85523,868,71);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('sed tristique in tempus sit','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',8850,608,67);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('ut erat id mauris vulputate','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',53602,807,59);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('ipsum praesent blandit lacinia erat','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',5117,894,11);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('luctus et ultrices posuere cubilia','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',387,329,68);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('lobortis vel dapibus at diam nam','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',80341,615,29);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('sollicitudin vitae consectetuer','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',18505,323,74);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('nec nisi vulputate nonummy maecenas tincidunt lacus at','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',58970,832,69);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('duis bibendum felis sed','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',75227,685,42);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('faucibus orci luctus et ultrices posuere','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',54619,320,62);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('suspendisse ornare consequat lectus in','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',6318,827,62);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('maecenas tristique est et','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',48955,1178,74);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('dui nec nisi volutpat eleifend donec ut dolor morbi vel','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',95523,454,63);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('porttitor lorem id ligula','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',2872,242,84);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('quis libero nullam sit amet turpis elementum ligula vehicula','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',36073,1026,76);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('sapien a libero nam dui proin leo odio','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',75554,1003,60);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',36909,696,17);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('enim lorem ipsum dolor sit amet consectetuer','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',94066,277,89);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('id pretium iaculis diam','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',84087,267,7);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('eros vestibulum ac','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',64821,179,62);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('congue vivamus metus arcu adipiscing','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',56045,797,44);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('velit donec diam neque vestibulum eget vulputate ut','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',96475,965,13);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('eu est congue elementum in hac','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',21360,706,5);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('molestie hendrerit at vulputate','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',53278,1124,38);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('a odio in hac habitasse platea dictumst','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',43035,478,72);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('primis in faucibus orci luctus','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',67262,62,53);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('ut blandit non interdum in ante vestibulum ante','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',64881,773,85);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('ut volutpat sapien arcu sed augue aliquam erat volutpat in','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',11582,389,41);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('lectus pellentesque at nulla suspendisse potenti cras in purus','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',26097,705,56);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('eget eleifend luctus ultricies eu nibh quisque id justo','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',66938,1013,84);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('curabitur convallis duis consequat dui nec','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',34573,476,23);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('cubilia curae donec pharetra magna vestibulum aliquet ultrices erat','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',52095,1148,21);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('vestibulum velit id pretium iaculis diam erat fermentum justo nec','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',19565,280,19);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('odio odio elementum eu interdum','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',73797,82,68);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('aenean sit amet justo','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',121,679,6);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('vestibulum ante ipsum','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',93012,360,28);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('mauris non ligula pellentesque ultrices phasellus id','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',39817,381,58);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('libero nullam sit amet turpis elementum ligula vehicula consequat','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',88289,182,6);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('sodales sed tincidunt eu felis fusce posuere felis sed','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',17989,182,26);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('condimentum neque sapien placerat ante','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',93359,203,38);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('massa donec dapibus duis at velit eu est congue','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',19877,343,23);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('praesent lectus vestibulum','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',1759,793,3);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('quisque ut erat curabitur gravida nisi','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',75087,1186,65);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('sollicitudin mi sit amet','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',27698,108,87);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('potenti in eleifend quam a odio in','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',27725,497,47);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('odio elementum eu interdum eu tincidunt in leo','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',24139,1080,7);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('habitasse platea dictumst aliquam augue','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',5635,511,16);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('eget semper rutrum nulla nunc purus phasellus in felis','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',4567,355,50);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('donec dapibus duis at velit eu','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',18372,266,53);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('non ligula pellentesque ultrices phasellus id','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',66309,868,31);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('mauris enim leo rhoncus sed vestibulum sit','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',6295,205,28);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('vestibulum quam sapien','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',48818,784,64);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('nulla sed accumsan felis ut at','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',25605,884,74);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('vivamus vestibulum sagittis sapien cum sociis natoque penatibus et','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',89849,984,77);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('molestie nibh in lectus pellentesque at nulla suspendisse potenti','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',68615,662,48);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('vestibulum ante ipsum primis in faucibus','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',56197,429,40);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('quam suspendisse potenti nullam porttitor lacus at','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',74180,953,37);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('suspendisse potenti cras in purus eu magna vulputate luctus cum','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',35381,1184,83);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('enim blandit mi in','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',18119,863,85);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('proin leo odio porttitor id consequat in consequat ut nulla','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',69989,1120,7);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('quis lectus suspendisse potenti in eleifend','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',10302,344,87);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('pulvinar nulla pede ullamcorper augue a','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',90862,311,82);
INSERT INTO videos (title, video_url, poster, views, duration, user_id) values ('orci mauris lacinia','http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4','https://picsum.photos/350/200',47709,732,45);

-- INSERT TAGS
insert into tags (name) values ('Comedy|Drama');
insert into tags (name) values ('Drama');
insert into tags (name) values ('Crime|Drama');
insert into tags (name) values ('Drama');
insert into tags (name) values ('Romance');
insert into tags (name) values ('Comedy|Drama|Romance');
insert into tags (name) values ('Action|Crime|Thriller');
insert into tags (name) values ('Action|Comedy');
insert into tags (name) values ('Comedy|Drama');
insert into tags (name) values ('Comedy');
insert into tags (name) values ('Comedy|Romance');
insert into tags (name) values ('Comedy');
insert into tags (name) values ('Crime|Drama');
insert into tags (name) values ('Action|Drama');
insert into tags (name) values ('Drama|Romance');

-- RELATION BETWEEN TAGS AND VIDEOS
insert into video_tags_bridge (tag_id, video_id) values (13,13);
insert into video_tags_bridge (tag_id, video_id) values (15,179);
insert into video_tags_bridge (tag_id, video_id) values (1,91);
insert into video_tags_bridge (tag_id, video_id) values (7,196);
insert into video_tags_bridge (tag_id, video_id) values (5,80);
insert into video_tags_bridge (tag_id, video_id) values (14,20);
insert into video_tags_bridge (tag_id, video_id) values (9,74);
insert into video_tags_bridge (tag_id, video_id) values (9,160);
insert into video_tags_bridge (tag_id, video_id) values (14,149);
insert into video_tags_bridge (tag_id, video_id) values (3,117);
insert into video_tags_bridge (tag_id, video_id) values (1,126);
insert into video_tags_bridge (tag_id, video_id) values (9,123);
insert into video_tags_bridge (tag_id, video_id) values (12,162);
insert into video_tags_bridge (tag_id, video_id) values (7,41);
insert into video_tags_bridge (tag_id, video_id) values (11,43);
insert into video_tags_bridge (tag_id, video_id) values (1,184);
insert into video_tags_bridge (tag_id, video_id) values (12,191);
insert into video_tags_bridge (tag_id, video_id) values (2,29);
insert into video_tags_bridge (tag_id, video_id) values (2,121);
insert into video_tags_bridge (tag_id, video_id) values (3,16);
insert into video_tags_bridge (tag_id, video_id) values (1,76);
insert into video_tags_bridge (tag_id, video_id) values (15,146);
insert into video_tags_bridge (tag_id, video_id) values (11,181);
insert into video_tags_bridge (tag_id, video_id) values (12,83);
insert into video_tags_bridge (tag_id, video_id) values (13,119);
insert into video_tags_bridge (tag_id, video_id) values (9,3);
insert into video_tags_bridge (tag_id, video_id) values (7,106);
insert into video_tags_bridge (tag_id, video_id) values (9,200);
insert into video_tags_bridge (tag_id, video_id) values (3,54);
insert into video_tags_bridge (tag_id, video_id) values (6,65);
insert into video_tags_bridge (tag_id, video_id) values (15,200);
insert into video_tags_bridge (tag_id, video_id) values (15,25);
insert into video_tags_bridge (tag_id, video_id) values (11,127);
insert into video_tags_bridge (tag_id, video_id) values (10,142);
insert into video_tags_bridge (tag_id, video_id) values (9,93);
insert into video_tags_bridge (tag_id, video_id) values (7,119);
insert into video_tags_bridge (tag_id, video_id) values (5,88);
insert into video_tags_bridge (tag_id, video_id) values (8,91);
insert into video_tags_bridge (tag_id, video_id) values (3,179);
insert into video_tags_bridge (tag_id, video_id) values (7,83);
insert into video_tags_bridge (tag_id, video_id) values (9,189);
insert into video_tags_bridge (tag_id, video_id) values (1,129);
insert into video_tags_bridge (tag_id, video_id) values (6,160);
insert into video_tags_bridge (tag_id, video_id) values (8,2);
insert into video_tags_bridge (tag_id, video_id) values (12,27);
insert into video_tags_bridge (tag_id, video_id) values (11,105);
insert into video_tags_bridge (tag_id, video_id) values (2,197);
insert into video_tags_bridge (tag_id, video_id) values (7,20);
insert into video_tags_bridge (tag_id, video_id) values (14,122);
insert into video_tags_bridge (tag_id, video_id) values (12,144);
insert into video_tags_bridge (tag_id, video_id) values (2,53);
insert into video_tags_bridge (tag_id, video_id) values (2,185);
insert into video_tags_bridge (tag_id, video_id) values (9,13);
insert into video_tags_bridge (tag_id, video_id) values (7,34);
insert into video_tags_bridge (tag_id, video_id) values (8,180);
insert into video_tags_bridge (tag_id, video_id) values (8,71);
insert into video_tags_bridge (tag_id, video_id) values (1,118);
insert into video_tags_bridge (tag_id, video_id) values (5,131);
insert into video_tags_bridge (tag_id, video_id) values (5,91);
insert into video_tags_bridge (tag_id, video_id) values (14,52);
insert into video_tags_bridge (tag_id, video_id) values (10,82);
insert into video_tags_bridge (tag_id, video_id) values (3,22);
insert into video_tags_bridge (tag_id, video_id) values (12,133);
insert into video_tags_bridge (tag_id, video_id) values (5,194);
insert into video_tags_bridge (tag_id, video_id) values (7,136);
insert into video_tags_bridge (tag_id, video_id) values (7,44);
insert into video_tags_bridge (tag_id, video_id) values (3,46);
insert into video_tags_bridge (tag_id, video_id) values (1,51);
insert into video_tags_bridge (tag_id, video_id) values (11,17);
insert into video_tags_bridge (tag_id, video_id) values (5,21);
insert into video_tags_bridge (tag_id, video_id) values (8,134);
insert into video_tags_bridge (tag_id, video_id) values (12,61);
insert into video_tags_bridge (tag_id, video_id) values (3,38);
insert into video_tags_bridge (tag_id, video_id) values (6,24);
insert into video_tags_bridge (tag_id, video_id) values (9,104);
insert into video_tags_bridge (tag_id, video_id) values (3,193);
insert into video_tags_bridge (tag_id, video_id) values (3,33);
insert into video_tags_bridge (tag_id, video_id) values (14,166);
insert into video_tags_bridge (tag_id, video_id) values (14,65);
insert into video_tags_bridge (tag_id, video_id) values (15,132);
insert into video_tags_bridge (tag_id, video_id) values (10,77);
insert into video_tags_bridge (tag_id, video_id) values (12,60);
insert into video_tags_bridge (tag_id, video_id) values (11,177);
insert into video_tags_bridge (tag_id, video_id) values (11,109);
insert into video_tags_bridge (tag_id, video_id) values (12,111);
insert into video_tags_bridge (tag_id, video_id) values (5,12);
insert into video_tags_bridge (tag_id, video_id) values (1,113);
insert into video_tags_bridge (tag_id, video_id) values (1,80);
insert into video_tags_bridge (tag_id, video_id) values (7,57);
insert into video_tags_bridge (tag_id, video_id) values (3,97);
insert into video_tags_bridge (tag_id, video_id) values (10,9);
insert into video_tags_bridge (tag_id, video_id) values (13,18);
insert into video_tags_bridge (tag_id, video_id) values (14,96);
insert into video_tags_bridge (tag_id, video_id) values (11,113);
insert into video_tags_bridge (tag_id, video_id) values (10,191);
insert into video_tags_bridge (tag_id, video_id) values (11,90);
insert into video_tags_bridge (tag_id, video_id) values (4,39);
insert into video_tags_bridge (tag_id, video_id) values (15,129);
insert into video_tags_bridge (tag_id, video_id) values (11,34);
insert into video_tags_bridge (tag_id, video_id) values (12,16);
insert into video_tags_bridge (tag_id, video_id) values (15,192);
insert into video_tags_bridge (tag_id, video_id) values (8,128);
insert into video_tags_bridge (tag_id, video_id) values (13,52);
insert into video_tags_bridge (tag_id, video_id) values (1,160);
insert into video_tags_bridge (tag_id, video_id) values (14,47);
insert into video_tags_bridge (tag_id, video_id) values (8,99);
insert into video_tags_bridge (tag_id, video_id) values (14,64);
insert into video_tags_bridge (tag_id, video_id) values (2,170);
insert into video_tags_bridge (tag_id, video_id) values (12,152);
insert into video_tags_bridge (tag_id, video_id) values (14,4);
insert into video_tags_bridge (tag_id, video_id) values (13,74);
insert into video_tags_bridge (tag_id, video_id) values (9,144);
insert into video_tags_bridge (tag_id, video_id) values (7,90);
insert into video_tags_bridge (tag_id, video_id) values (13,142);
insert into video_tags_bridge (tag_id, video_id) values (4,112);
insert into video_tags_bridge (tag_id, video_id) values (11,100);
insert into video_tags_bridge (tag_id, video_id) values (4,41);
insert into video_tags_bridge (tag_id, video_id) values (3,108);
insert into video_tags_bridge (tag_id, video_id) values (1,58);
insert into video_tags_bridge (tag_id, video_id) values (10,196);
insert into video_tags_bridge (tag_id, video_id) values (12,94);
insert into video_tags_bridge (tag_id, video_id) values (11,62);
insert into video_tags_bridge (tag_id, video_id) values (14,122);
insert into video_tags_bridge (tag_id, video_id) values (14,81);
insert into video_tags_bridge (tag_id, video_id) values (6,119);
insert into video_tags_bridge (tag_id, video_id) values (3,185);
insert into video_tags_bridge (tag_id, video_id) values (4,106);
insert into video_tags_bridge (tag_id, video_id) values (13,107);
insert into video_tags_bridge (tag_id, video_id) values (5,70);
insert into video_tags_bridge (tag_id, video_id) values (2,73);
insert into video_tags_bridge (tag_id, video_id) values (7,160);
insert into video_tags_bridge (tag_id, video_id) values (12,134);
insert into video_tags_bridge (tag_id, video_id) values (8,4);
insert into video_tags_bridge (tag_id, video_id) values (8,63);
insert into video_tags_bridge (tag_id, video_id) values (3,158);
insert into video_tags_bridge (tag_id, video_id) values (1,189);
insert into video_tags_bridge (tag_id, video_id) values (11,15);
insert into video_tags_bridge (tag_id, video_id) values (8,188);
insert into video_tags_bridge (tag_id, video_id) values (8,155);
insert into video_tags_bridge (tag_id, video_id) values (11,171);
insert into video_tags_bridge (tag_id, video_id) values (7,22);
insert into video_tags_bridge (tag_id, video_id) values (6,76);
insert into video_tags_bridge (tag_id, video_id) values (4,44);
insert into video_tags_bridge (tag_id, video_id) values (14,161);
insert into video_tags_bridge (tag_id, video_id) values (7,117);
insert into video_tags_bridge (tag_id, video_id) values (8,87);
insert into video_tags_bridge (tag_id, video_id) values (3,199);
insert into video_tags_bridge (tag_id, video_id) values (5,187);
insert into video_tags_bridge (tag_id, video_id) values (4,160);
insert into video_tags_bridge (tag_id, video_id) values (9,39);
insert into video_tags_bridge (tag_id, video_id) values (7,178);
insert into video_tags_bridge (tag_id, video_id) values (14,36);
insert into video_tags_bridge (tag_id, video_id) values (2,190);
insert into video_tags_bridge (tag_id, video_id) values (14,124);
insert into video_tags_bridge (tag_id, video_id) values (6,181);
insert into video_tags_bridge (tag_id, video_id) values (10,150);
insert into video_tags_bridge (tag_id, video_id) values (5,28);
insert into video_tags_bridge (tag_id, video_id) values (8,171);
insert into video_tags_bridge (tag_id, video_id) values (11,31);
insert into video_tags_bridge (tag_id, video_id) values (14,185);
insert into video_tags_bridge (tag_id, video_id) values (11,89);
insert into video_tags_bridge (tag_id, video_id) values (1,145);
insert into video_tags_bridge (tag_id, video_id) values (15,167);
insert into video_tags_bridge (tag_id, video_id) values (10,143);
insert into video_tags_bridge (tag_id, video_id) values (8,132);
insert into video_tags_bridge (tag_id, video_id) values (10,32);
insert into video_tags_bridge (tag_id, video_id) values (10,41);
insert into video_tags_bridge (tag_id, video_id) values (15,118);
insert into video_tags_bridge (tag_id, video_id) values (5,183);
insert into video_tags_bridge (tag_id, video_id) values (12,96);
insert into video_tags_bridge (tag_id, video_id) values (1,53);
insert into video_tags_bridge (tag_id, video_id) values (13,197);
insert into video_tags_bridge (tag_id, video_id) values (4,12);
insert into video_tags_bridge (tag_id, video_id) values (14,100);
insert into video_tags_bridge (tag_id, video_id) values (13,85);
insert into video_tags_bridge (tag_id, video_id) values (12,105);
insert into video_tags_bridge (tag_id, video_id) values (14,12);
insert into video_tags_bridge (tag_id, video_id) values (13,75);
insert into video_tags_bridge (tag_id, video_id) values (2,141);
insert into video_tags_bridge (tag_id, video_id) values (5,127);
insert into video_tags_bridge (tag_id, video_id) values (6,169);
insert into video_tags_bridge (tag_id, video_id) values (10,149);
insert into video_tags_bridge (tag_id, video_id) values (11,150);
insert into video_tags_bridge (tag_id, video_id) values (14,163);
insert into video_tags_bridge (tag_id, video_id) values (6,115);
insert into video_tags_bridge (tag_id, video_id) values (5,15);
insert into video_tags_bridge (tag_id, video_id) values (6,128);
insert into video_tags_bridge (tag_id, video_id) values (6,179);
insert into video_tags_bridge (tag_id, video_id) values (10,26);
insert into video_tags_bridge (tag_id, video_id) values (7,170);
insert into video_tags_bridge (tag_id, video_id) values (7,93);
insert into video_tags_bridge (tag_id, video_id) values (9,122);
insert into video_tags_bridge (tag_id, video_id) values (4,126);
insert into video_tags_bridge (tag_id, video_id) values (5,167);
insert into video_tags_bridge (tag_id, video_id) values (9,162);
insert into video_tags_bridge (tag_id, video_id) values (11,16);
insert into video_tags_bridge (tag_id, video_id) values (1,129);
insert into video_tags_bridge (tag_id, video_id) values (11,101);
insert into video_tags_bridge (tag_id, video_id) values (4,35);
insert into video_tags_bridge (tag_id, video_id) values (5,31);
insert into video_tags_bridge (tag_id, video_id) values (10,47);
insert into video_tags_bridge (tag_id, video_id) values (5,19);
insert into video_tags_bridge (tag_id, video_id) values (1,109);
insert into video_tags_bridge (tag_id, video_id) values (8,193);
insert into video_tags_bridge (tag_id, video_id) values (15,54);
insert into video_tags_bridge (tag_id, video_id) values (14,11);
insert into video_tags_bridge (tag_id, video_id) values (11,82);
insert into video_tags_bridge (tag_id, video_id) values (10,49);
insert into video_tags_bridge (tag_id, video_id) values (11,4);
insert into video_tags_bridge (tag_id, video_id) values (7,139);
insert into video_tags_bridge (tag_id, video_id) values (14,58);
insert into video_tags_bridge (tag_id, video_id) values (12,124);
insert into video_tags_bridge (tag_id, video_id) values (3,91);
insert into video_tags_bridge (tag_id, video_id) values (5,137);
insert into video_tags_bridge (tag_id, video_id) values (4,140);
insert into video_tags_bridge (tag_id, video_id) values (2,85);
insert into video_tags_bridge (tag_id, video_id) values (15,79);
insert into video_tags_bridge (tag_id, video_id) values (6,111);
insert into video_tags_bridge (tag_id, video_id) values (9,127);
insert into video_tags_bridge (tag_id, video_id) values (10,151);
insert into video_tags_bridge (tag_id, video_id) values (2,55);
insert into video_tags_bridge (tag_id, video_id) values (7,111);
insert into video_tags_bridge (tag_id, video_id) values (4,114);
insert into video_tags_bridge (tag_id, video_id) values (2,120);
insert into video_tags_bridge (tag_id, video_id) values (13,59);
insert into video_tags_bridge (tag_id, video_id) values (6,40);
insert into video_tags_bridge (tag_id, video_id) values (12,139);
insert into video_tags_bridge (tag_id, video_id) values (3,192);
insert into video_tags_bridge (tag_id, video_id) values (2,137);
insert into video_tags_bridge (tag_id, video_id) values (2,45);
insert into video_tags_bridge (tag_id, video_id) values (5,148);
insert into video_tags_bridge (tag_id, video_id) values (7,188);
insert into video_tags_bridge (tag_id, video_id) values (3,113);
insert into video_tags_bridge (tag_id, video_id) values (6,195);
insert into video_tags_bridge (tag_id, video_id) values (3,112);
insert into video_tags_bridge (tag_id, video_id) values (12,61);
insert into video_tags_bridge (tag_id, video_id) values (8,111);
insert into video_tags_bridge (tag_id, video_id) values (6,75);
insert into video_tags_bridge (tag_id, video_id) values (1,35);
insert into video_tags_bridge (tag_id, video_id) values (7,88);
insert into video_tags_bridge (tag_id, video_id) values (11,118);
insert into video_tags_bridge (tag_id, video_id) values (9,157);
insert into video_tags_bridge (tag_id, video_id) values (7,61);
insert into video_tags_bridge (tag_id, video_id) values (13,101);
insert into video_tags_bridge (tag_id, video_id) values (1,52);
insert into video_tags_bridge (tag_id, video_id) values (1,140);
insert into video_tags_bridge (tag_id, video_id) values (1,10);
insert into video_tags_bridge (tag_id, video_id) values (3,104);
insert into video_tags_bridge (tag_id, video_id) values (13,135);
insert into video_tags_bridge (tag_id, video_id) values (2,76);
insert into video_tags_bridge (tag_id, video_id) values (8,67);
insert into video_tags_bridge (tag_id, video_id) values (7,76);
insert into video_tags_bridge (tag_id, video_id) values (10,94);
insert into video_tags_bridge (tag_id, video_id) values (4,194);
insert into video_tags_bridge (tag_id, video_id) values (14,59);
insert into video_tags_bridge (tag_id, video_id) values (7,122);
insert into video_tags_bridge (tag_id, video_id) values (7,26);
insert into video_tags_bridge (tag_id, video_id) values (4,62);
insert into video_tags_bridge (tag_id, video_id) values (5,100);
insert into video_tags_bridge (tag_id, video_id) values (9,54);
insert into video_tags_bridge (tag_id, video_id) values (10,31);
insert into video_tags_bridge (tag_id, video_id) values (2,12);
insert into video_tags_bridge (tag_id, video_id) values (5,30);
insert into video_tags_bridge (tag_id, video_id) values (12,82);
insert into video_tags_bridge (tag_id, video_id) values (10,152);
insert into video_tags_bridge (tag_id, video_id) values (4,128);
insert into video_tags_bridge (tag_id, video_id) values (12,188);
insert into video_tags_bridge (tag_id, video_id) values (6,112);
insert into video_tags_bridge (tag_id, video_id) values (8,103);
insert into video_tags_bridge (tag_id, video_id) values (5,41);
insert into video_tags_bridge (tag_id, video_id) values (7,129);
insert into video_tags_bridge (tag_id, video_id) values (9,158);
insert into video_tags_bridge (tag_id, video_id) values (8,52);
insert into video_tags_bridge (tag_id, video_id) values (2,12);
insert into video_tags_bridge (tag_id, video_id) values (3,169);
insert into video_tags_bridge (tag_id, video_id) values (11,147);
insert into video_tags_bridge (tag_id, video_id) values (3,97);
insert into video_tags_bridge (tag_id, video_id) values (13,103);
insert into video_tags_bridge (tag_id, video_id) values (12,81);
insert into video_tags_bridge (tag_id, video_id) values (11,73);
insert into video_tags_bridge (tag_id, video_id) values (11,188);
insert into video_tags_bridge (tag_id, video_id) values (7,121);
insert into video_tags_bridge (tag_id, video_id) values (8,29);
insert into video_tags_bridge (tag_id, video_id) values (15,18);
insert into video_tags_bridge (tag_id, video_id) values (1,69);
insert into video_tags_bridge (tag_id, video_id) values (13,184);
insert into video_tags_bridge (tag_id, video_id) values (14,162);
insert into video_tags_bridge (tag_id, video_id) values (6,150);
insert into video_tags_bridge (tag_id, video_id) values (1,45);
insert into video_tags_bridge (tag_id, video_id) values (1,166);
insert into video_tags_bridge (tag_id, video_id) values (9,187);
insert into video_tags_bridge (tag_id, video_id) values (1,88);
insert into video_tags_bridge (tag_id, video_id) values (14,135);
insert into video_tags_bridge (tag_id, video_id) values (12,51);
insert into video_tags_bridge (tag_id, video_id) values (11,134);
insert into video_tags_bridge (tag_id, video_id) values (2,180);
insert into video_tags_bridge (tag_id, video_id) values (12,52);
insert into video_tags_bridge (tag_id, video_id) values (9,195);
insert into video_tags_bridge (tag_id, video_id) values (10,66);